import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "../styles/globals.css";
import { cn } from "@/lib/utils";

const beVietnamPro = Be_Vietnam_Pro({
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-be-vietnam-pro",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "antialiased w-full h-screen flex flex-col items-center",
          beVietnamPro.variable,
        )}
      >
        {children}
      </body>
    </html>
  );
}
